image:
  repository: ghcr.io/matrix-construct/tuwunel
  tag: v1.4.1
  pullPolicy: IfNotPresent

config:
  server_name: "example.org"
  max_request_size: "20000000"
  allow_registration: false
  # You must set registration token below to enable registrations
  registration_token: "supa-dupa-secret-token"
  allow_federation: false
  trusted_servers: []
  ## If you are delegating your domain, uncomment the next line and add your
  ## delegated domain.  This will add it to the ingress and setup the proper
  ## environment variables.
  # delegatedDomain: example.example.org

extraEnv: []

## Add additional labels to all resources
extraLabels: {}

service:
  annotations: {}
  type: ClusterIP
  clusterIP: "None"

  port: 80
  ## List of IP addresses at which the service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  loadBalancerIP: ""
  loadBalancerSourceRanges: []

ingress:
  enabled: false
  class:
  # You will probably want to provide either large upload size limits, or no
  #    upload size limit; for example, if using nginx-ingress, include
  #    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  annotations: {}
  path: /
  hosts:
    - tuwunel
  tls: false

## Persist configuration to a persistent volume
persistence:
  ## Data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If unset, storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  data:
    enabled: true
    existingClaim:
    storageClass:
    accessMode: ReadWriteOnce
    size: 16Gi

resources:
  requests:
    cpu: "1"
    memory: "256Mi"
  limits:
    cpu: "2"
    memory: "512Mi"

nodeSelector: {}

tolerations: []

affinity: {}
