{{- if .Values.ingress.enabled -}}
{{- $fullName := include "tuwunel.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $delegatedDomain := "" }}
{{- $isDelegatedDomain := .Values.config.global.well_known.server }}
{{- if $isDelegatedDomain }}
{{- $delegatedDomain = mustRegexReplaceAll ":[0-9]+" .Values.config.global.well_known.server "" }}
{{- end }}
{{- $new := false }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
apiVersion: networking.k8s.io/v1
{{- $new = true }}
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "tuwunel.labels" . | nindent 4 }}
  annotations:
    {{- if not $new }}
    kubernetes.io/ingress.class: {{ required "If ingress.enabled is set to true, ingress.class is required" .Values.ingress.class | quote }}
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if $new }}
  ingressClassName: {{ required "If ingress.enabled is set to true, ingress.class is required" .Values.ingress.class | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.server_name }}
        - {{ $delegatedDomain }}
      {{- range .Values.ingress.extraHosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ $fullName }}-tls
  {{- end }}
  rules:
    {{- if $isDelegatedDomain }}
    - host: {{ .Values.server_name }}
      http:
        paths:
          - path: "/.well-known/matrix"
            {{- if $new }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if $new }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
              {{- end }}
    {{- end }}
    {{- if $isDelegatedDomain }}
    - host: {{ $delegatedDomain }}
    {{- else }}
    - host: {{ .Values.server_name }}
    {{- end }}
      http:
        paths:
          - path: {{ $ingressPath }}
            {{- if $new }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if $new }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
              {{- end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            {{- if $new }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if $new }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
              {{- end }}
    {{- end }}
{{- end }}

